/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package galactic_messenger;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertTrue(true, "hello");
    }
}